services:
  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  backend:
    build: ../backend/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../data/:/app/data/

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data:
  static:
  media: