# Generated by Django 5.2.1 on 2025-05-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
    ]
